#
# This is a docker-compose file to build and start all Lakeside Mutual
# applications in a single command. Note that the applications will all
# run in production mode, so there won't be any live-reloading of changes
# or other development features. For development, we recommend to start
# the applications invidually or use the run_all_applications scripts.
#
# To build the Docker images:
#   docker-compose build
#
# To run the applications:
#   docker-compose up
#
# To shut down the applications, simply terminate the previous command.
#
version: "3"
services:
  customer-core:
    build: customer-core
    image: lakesidemutual/customer-core
    environment:
      - "SPRING_BOOT_ADMIN_CLIENT_URL=http://spring-boot-admin:9000"
    ports:
      - "8110:8110"    
  customer-management-backend:
    build: customer-management-backend
    image: lakesidemutual/customer-management-backend
    depends_on:
      - customer-core
    environment:
      - "CUSTOMERCORE_BASEURL=http://customer-core:8110"
      - "SPRING_BOOT_ADMIN_CLIENT_URL=http://spring-boot-admin:9000"
    ports:
      - "8100:8100"
  customer-management-frontend:
    build: customer-management-frontend
    image: lakesidemutual/customer-management-frontend
    depends_on:
      - customer-management-backend
    environment:
      - "REACT_APP_CUSTOMER_MANAGEMENT_BACKEND=http://customer-management-backend:8100"
    ports:
      - "80:80"